# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\"+\n\x0eStudentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x1e\n\x0cStudentReply\x12\x0e\n\x06\x63ourse\x18\x01 \x01(\x05\x32\x36\n\x07Greeter\x12+\n\x07Student\x12\x0f.StudentRequest\x1a\r.StudentReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STUDENTREQUEST']._serialized_start=20
  _globals['_STUDENTREQUEST']._serialized_end=63
  _globals['_STUDENTREPLY']._serialized_start=65
  _globals['_STUDENTREPLY']._serialized_end=95
  _globals['_GREETER']._serialized_start=97
  _globals['_GREETER']._serialized_end=151
# @@protoc_insertion_point(module_scope)
